---
name: Build and Deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    concurrency: deploy-${{ github.ref }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: out

      - uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: lint
        run: make lint


      - name: package
        run: make

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
